[package]
name = "plc"
version = "0.1.0"
authors = ["trolleyman <cgtrolley@gmail.com>"]

[dependencies]
gtk = "0.0.6"
#gtk-sys = "0.2.1"
gdk = "0.2.0"
cairo-rs = "0.0.7"

[dependencies.logic]
path = "logic/"
